stages:
  - build
  - deploy

build_project:
  stage: build
  only:
    - develop
  script:
    - docker-compose -f stage-dev.yml build
  tags:
    - apaweb

deploy_project:
  stage: deploy
  only:
    - develop
  script:
    - docker-compose -f stage-dev.yml up -d
    - sleep 10
    - docker exec -d apawebapp php artisan migrate:fresh --seed
  tags:
    - apaweb
