stages:
  - build
  - test
  - deploy

build_project:
  stage: build
  only:
    - main
  script:
    - docker-compose -f stage-dev.yml build
  tags:
    - apaweb

test_project:
  stage: test
  only:
    - main
  script:
    - curl https://sonarqube-agenal.ml/
  tags:
    - apaweb

deploy_project:
  stage: deploy
  only:
    - main
  script:
    - docker-compose -f stage-dev.yml up -d
    - sleep 10
    - docker exec -d apawebapp php artisan migrate:fresh --seed
  tags:
    - apaweb
